
target_compile_definitions(${PROJECT_NAME} PRIVATE LIB_EXPORT)
set(OUTPUT_DIR ${CMAKE_SOURCE_DIR})

set_target_properties(${PROJECT_NAME} PROPERTIES 
    RUNTIME_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIR}/bin
    LIBRARY_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIR}/${PROJECT_NAME}/lib
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIR}/${PROJECT_NAME}/lib
    RUNTIME_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIR}/bin
    LIBRARY_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIR}/${PROJECT_NAME}/lib
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIR}/${PROJECT_NAME}/lib
    OUTPUT_NAME "$<IF:$<CONFIG:Debug>,${PROJECT_NAME}d,${PROJECT_NAME}>")

set(CMAKE_INSTALL_PREFIX ${OUTPUT_DIR}/installed/)

install(TARGETS ${PROJECT_NAME}
    EXPORT ${PROJECT_NAME}Targets
    LIBRARY DESTINATION lib
    ARCHIVE DESTINATION lib
    RUNTIME DESTINATION bin
    INCLUDES DESTINATION include
)

install(FILES
    ${PROJECT_NAME}/include/*.hpp
    DESTINATION ${PROJECT_NAME}/include/${PROJECT_NAME}
)

install(FILES
    CommonDef/include/CommonDef/*.h
    DESTINATION ${PROJECT_NAME}/include/CommonDef
)

install(EXPORT ${PROJECT_NAME}Targets
    FILE ${PROJECT_NAME}Config.cmake
    NAMESPACE ${PROJECT_NAME}::
    DESTINATION lib/cmake/${PROJECT_NAME}
)
